ALTER TABLE app_user ADD COLUMN IF NOT EXISTS banned BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS banned_at TIMESTAMP NULL;
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS banned_reason VARCHAR(500) NULL;

